### ISSUE TITLE
That's amazing!

### ISSUE THREAD

**Issue by alex-bender** [CoatiSoftware/SourcetrailPythonIndexer#1]
I've been waiting for that for a while and it's really great that this project started.
Would be glad to help somehow if it's possible at all.
Thanks!

**Comment by mlangkabel** [comment]
Hi @alex-bender, thank you for your kind words!
The project is coming along really well and already looks quite promising.

There are lots of ways you can help and get involved. Maybe we should update the Readme soon with a section about contributing ;)

But for now, here are some ideas on what would help:
* Spread the word. The more people want this project to grow, the greater the motivation for the developers to get things done.
* Test the indexer on your projects. There are still things that are not handled (to name only one: recording information on which modules get imported by which files). If you find anything, just create an issue here. Do the same if you find something that works in most cases, but is still broken for some edge cases. Best would be if we get some sample code snippet that illustrates the issue, so we can use it as a test case for our continuous integration and no one will never break that case again.
* Work on the code. Don't be shy here, you can also do some refactoring if you think that it benefits the readability or the maintainability of the code. Still, no matter if you just want to work on cosmetics or implement new features, it would be best if you create an issue here on the issue tracker before you actually start creating pull requests, so that we can discuss those changes first and thus raise the probability that those changes will get pulled as soon as possible.

**Comment by alex-bender** [comment]
That's really cool! I will definitely do what I can to help.
