### ISSUE TITLE
Return code 255 error

### ISSUE THREAD

**Issue by securisec** [CoatiSoftware/SourcetrailPythonIndexer#13]
Wondering if I get some direction here. Trying this using:
Sourcetrail 2019.1.11
Python 3.6.5
OSX

Getting an error even when trying to do this on a single file
```command "python3 /private/tmp/SourcetrailPythonIndexer/run.py --source-file-path="/private/tmp/testproject/testproject/__init__.py" --database-file-path="/private/tmp/test/testproject.srctrldb_tmp"" returned code "255" with message "File not found or resource error occurred." and output "".```

The same error applies to any files within the project.

I am getting the same issue from both the release versions, and from building it myself. Of note, this issue is happening in the Sourcetrail app. It works fine when i am using the command line to process one file. Hoping to leverage the App for a directory of files

Thanks!

**Comment by mlangkabel** [comment]
We are currently working on creating downloadable packages for each OS that contain a freezed version of the Python indexer which does not access the installed python environment (issue #11). Maybe this will fix the issue and make this workaround obsolete.

**Comment by mlangkabel** [comment]
I guess that you closed the issue means that the comment of @egraether helped to fix your issue?

**Comment by securisec** [comment]
Yes, the comment by @egraether was super helpful. I will toy with some ideas on freezing the code for osx, and if it works, i will submit a pull request.

**Comment by mlangkabel** [comment]
That sounds great! You can take a look at the [pyInstaller](https://www.pyinstaller.org/). We already have a [config file](https://github.com/CoatiSoftware/SourcetrailPythonIndexer/blob/master/freezing.spec) for that one which we use in our Appveyor CI to build the Windows package. Would be great if we could re-use that config for Mac and Linux, too, so we'd have only one place that we need to change if we add anything.

Best thing would be to have a travis based CI that does this freezing for mac. That would be really great! If you want to, you can try to set this up. In that case you will need to add one version of the sourcetraildb python bindings to this repository so that it can be included in the package :)

If you just want to take care of the freezing, maybe write a script that we can later use from within the CI!

**Comment by mlangkabel** [comment]
@securisec: Ok, the code freezing using pyInstaller is now in place for all supported operating systems. If you find out anything that we need to add or consider, please let us know :)

**Comment by securisec** [comment]
Awesome! Will do!

**Comment by securisec** [comment]
@mlangkabel just wanted to throw it out there that the volatility spec file is pretty neat and compact for all the supported OS's https://github.com/volatilityfoundation/volatility/blob/master/pyinstaller.spec

**Comment by mlangkabel** [comment]
That one looks simpler than ours :)

**Comment by securisec** [comment]
Where are the linux and osx builds being housed at the moment?

**Comment by mlangkabel** [comment]
They are all built by our CI here on this repository.
* Windows builds are done by [this Appveyor script](https://github.com/CoatiSoftware/SourcetrailPythonIndexer/blob/master/appveyor.yml)
* Mac and Linux builds are done by [this Travis script](https://github.com/CoatiSoftware/SourcetrailPythonIndexer/blob/master/.travis.yml)

You can view the Travis pipeline here: [https://travis-ci.org/CoatiSoftware/SourcetrailPythonIndexer](https://travis-ci.org/CoatiSoftware/SourcetrailPythonIndexer)

I think for Travis the freezing is only performed for a deploy (that's when the CI pipeline creates artefacts and uploads them to GitHub). That does not happen for each commit, but only for every tag.

**Comment by Gansgar** [comment]
I'm sadly hitting upon the same wall on Ubuntu 20.04. The Appimage (2020.4.35} also doesn't work.
