### ISSUE TITLE
`import .. as` problem

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/SourcetrailPythonIndexer#52]
Hello..

The following:

`import logging as logging_module`

Yields this error:

`Imported symbol named "logging" has not been found.`

**Comment by mlangkabel** [comment]
Hi @TTimo, can you provide a little bit more info, please? 
* Where is the logging module located? Somewhere relative to your project files? Or is it part of your Python environment? 
* Which Python version are you using? 
* What Python environment is Sourcetrail using? Did you specify a Python Environment inside the Sourcetrail Project Settings? If not you can check the used Python environment in the log after enabling verbose logging (if you wanna do that, make sure to index only one small file, otherwise it may take a while).

**Comment by TTimo** [comment]
Aand .. it looks like it was a one time thing, I can't reproduce anymore. I reindexed (the project didn't change, or barely), and the error wasn't reported the second time .. sorry!

**Comment by mlangkabel** [comment]
Alright, thanks for the update!

**Comment by comperem** [comment]
I received a similar error with `datetime` and `socket` imports. These are clearly available but the error did not surface again after closing and re-opening the project. Python 3.8.10 and SourceTrail 2021.1.30. All defaults for new project.
