### ISSUE TITLE
__init__ causing links to be shown that should not be

### ISSUE THREAD

**Issue by rwalroth** [CoatiSoftware/SourcetrailPythonIndexer#64]
First, this is a fantastic program and I am blown away by how useful it is. But there is a problem I have encountered, that \_\_init__ is causing basically every class to show up as referencing each other: 
![image](https://user-images.githubusercontent.com/31414518/77137002-401bf980-6a29-11ea-911a-d13749ec6aec.png)
The links are all ambiguous, and disabling ambiguous post processing is a quick fix but then other ambiguous links I would like to see don't show up. Are there ways to delete edges I know are not needed or to toggle ambiguous edges on and off (doesn't seem like totally re-indexing the project should be necessary)?

**Comment by mlangkabel** [comment]
@rwalroth, thanks for bringing this up. If you have lots of ambiguous edges, then you are probably only using the "shallow indexing". You shouldn't encounter those issues, if you run the indepth indexing. But of course, that takes much longer to finish.

Usually, resolving those ambiguous edges works fine, but "init" is a special case because that method has the same name in every class. 

Let me take a look, maybe we can fix this.

**Comment by mlangkabel** [comment]
Implemented with Sourcetrail pull requests [951](https://github.com/CoatiSoftware/Sourcetrail/pull/951) and [964](https://github.com/CoatiSoftware/Sourcetrail/pull/964). This feature should be available in our next release.
